### ISSUE TITLE
Missing code for merge_substates in "Using the Framework" RTD

### ISSUE THREAD

**Issue by charleswhchan** [dwavesystems/dwave-hybrid#142]
Reading along the examples provided in "[Using the Framework](https://github.com/dwavesystems/dwave-hybrid/blob/808260d27dcfa79cf96eba751c529e73e630db23/docs/intro/using.rst#L157)", it is not apparent where `merge_substates` is defined.

Do we need to include `def merge_substates()` in the document from the following file?
https://github.com/dwavesystems/dwave-hybrid/blob/2614c00c07a6bc867292f66e19b73f9e453c8d37/examples/qbsolv-like-alt.py

**Comment by randomir** [comment]
Yes. I think we should, for now, just include the `merge_substates`' code in the docs, @JoelPasvolsky. That is, until (or if) we create a top-level block for hstack-ing of subsamples.

**Comment by JoelPasvolsky** [comment]
@randomir, I'd want to move `def merge_substates(_, substates):` from its current location to utils.py before getting it picked up by utilities.rst. TBH it seems to belong more to primitive methods but you have your two stacking functions there like a mama and papa waiting to reunite with baby merge_substates. What do you think?

**Comment by randomir** [comment]
As it is, `merge_substates` from the qbsolv-like example is too specific -- it is more of an example of `Reduce/Lambda` use than anything else.

We could/should create all `{hstack, vstack} x {samples, subsamples}` block variants - probably under `hybrid.composers`. Right now, we only have "vstack of samples" available as `hybrid.composers.MergeSamples`.

**Comment by JoelPasvolsky** [comment]
Should we talk about this next week, see how to best schedule all the work for what we currently have and what we'll like have in two months?
