### ISSUE TITLE
Boltzmann Machine Implementation

### ISSUE THREAD

**Issue by Bhaney44** [dwavesystems/dwave-hybrid#198]
Hi,

I hope this note finds everyone well. I am working on implementing a Boltzmann Machine (BM) and am having some trouble. I started a [repository](https://github.com/Bhaney44/Quantum-Boltzmann-Machine) for the project. The repository has the complete code as well as some of my other Leap code examples. I tried to start by logging into LEAP and running the following code in a Jupyter Notebook to setup a Graph and BM object:

```
from dwave_bm.rbm import BM

# Model dimensions.
num_visible = 10

# the hidden layer is a bipartite graph of 9 by 5
num_hidden = [9, 5] 

# Create the Boltzmann machine object
r = BM(num_visible=num_visible, num_hidden=num_hidden)
r
```
However, I am getting a response:

`ModuleNotFoundError: No module named 'dwave_bm'`

I am not sure what is causing the error. I am also having a lot of trouble finding documentation for the dwave_bm module. I am considering trying to use the dwave_networkx package instead, to try and create a BM using a a graph. An additional questions is whether the fact I am running the system through a Jupyter notebook could be causing the problem. I am wondering whether if I ran the script from the command line, I may have more success. 

Generally, my goal is to implement a simple BM model on the QPU, as demonstrated in John Dorband's paper [A Boltzmann Machine Implementation for the D-Wave](https://arxiv.org/abs/1606.06123). I will probably use the [MNIST Dataset ](http://yann.lecun.com/exdb/mnist/), because it was the one John use and it seems the most straightforward. 

In sum, I would really appreciate any thoughts, guidance, or suggestions on how to proceed.

With thanks,

Brian

**Comment by Bhaney44** [comment]
> I'm not sure if those materials are still available to you, you should check with the course organizer. But `dwave_bm` package is not publicly available.

I actually don't remember who the course organizer was or their contact information. However, I would like access to `dwave_bm`. Is there a contact method you may be able to provide, or other information on how I can gain access? Thanks!

**Comment by randomir** [comment]
Hey Brian, unfortunately that package is no longer available. Even if it would be made available for you, you still wouldn't be able to use it with our stable/supported libraries.

We don't discuss BMs in our docs, but [this page](https://docs.dwavesys.com/docs/latest/handbook_problems.html#boltzmann-distribution) might be a good starting point if you decide to implement it yourself.

**Comment by Bhaney44** [comment]
Ok - Thank you.
