### ISSUE TITLE
Error message for branch with single component

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-hybrid#207]
```
>>> hybrid.Branch(hybrid.Identity()).run(state_start).result()
```
gives error:
```
ValueError: branch has to contain at least one component
```

It's currently more accurate for the error to say "branch has to contain **more than** one component" but preferably hybrid.Branch would accept a single Runnable--would be useful for debugging code.

Thanks!

**Comment by randomir** [comment]
`Branch` *does* accept a single component, because that's very useful, as well as common use-case.

The problem is in the way you're constructing that branch. See [docs](https://docs.ocean.dwavesys.com/projects/hybrid/en/latest/reference/flow.html#hybrid.flow.Branch).

```
hybrid.Branch((hybrid.Identity(),)).run(hybrid.State()).result()
```
