### ISSUE TITLE
class HybridSampler should include the info field in conversion

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dwave-hybrid#210]
Current implementation is
```
return dimod.SampleSet.from_future(final_state, result_hook=lambda f: f.result().samples)
```
So the hybrid.State is correctly stripped of the `problem` field but unfortunately also stripped of the `info` field, which is a supported field in dimod.SampleSet and so should be preserved.

Please update the result_hook to include `info` if present in the hybrid.State

Thanks!

**Comment by randomir** [comment]
I'm not sure I understand your request, because the `info` field from the final state **is included** in the returned `SampleSet`.

Can you provide a working example that demonstrates the problem you're seeing?

**Comment by JoelPasvolsky** [comment]
Sorry, I should have explicitly said state-level info or other optional fields. I see high value in these for workflows and would like the option to bring them into the final SampleSet, maybe with some flag parameter in HybridSampler().

Here's an example:
```
wf = hybrid.Lambda(lambda _, s: s.updated(info="some info")) | hybrid.TabuProblemSampler()
wf.run(state).result()
```
The output state has an `info` (or other informational) state that can be hugely useful in tracking and debugging complex workflows, or even functionally in workflows. I'd like those fields preserved into the SampleSet `info` field (merged or overwritten or renamed, perhaps based on a parameter in HybridSampler).

Then for the conversion:
```
ds = hybrid.HybridSampler(hybrid.Lambda(lambda _, s: s.updated(info="some info")) | 
                          hybrid.TabuProblemSampler())
solution = ds.sample(bqm)
```
I'd get my workflow information  back in the returned SampleSet under it's `info` field.

**Comment by randomir** [comment]
OK, that makes sense.
