### ISSUE TITLE
Potential dependency conflicts between dwave-hybrid and numpy

### ISSUE THREAD

**Issue by NeolithEra** [dwavesystems/dwave-hybrid#224]
Hi, as shown in the following full dependency graph of **_dwave-hybrid_**, **_dwave-hybrid_** requires **_numpy >=1.15.0,<2.0.0_**, **_dwave-hybrid_** requires **_dimod >=0.8.11_** (dimod 0.9.1 will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_dimod 0.9.1_** transitively introduces **_numpy >=1.16.0,<2.0.0_**.

Obviously, there are multiple version constraints set for numpy in this project. However, according to pip's “_first found wins_” installation strategy, **_numpy 1.18.4_** (i.e., the newest version satisfying constraint >=1.15.0,<2.0.0) is the actually installed version.

Although the first found package version **_numpy 1.18.4_** just satisfies the later dependency constraint （**_numpy >=1.16.0,<2.0.0_**), such installed version is very close to the upper bound of the version constraint of Numpy specified by **_dimod0.9.1_** .

Once **_dimod_** upgrades，its newest version will be installed, as **_dwave-hybrid_** does not specify the upper bound of version constraint for **_dimod_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_dimod_** version introduces a higher version of Numpy, violating its another version constraint **_>=1.15.0,<2.0.0_**.

According to the release history of **_dimod_**, it habitually upgrates **_Numpy_** in its recent releases. For instance, **_dimod 0.7.0_** upgrated Numpy’s constraint from **_>=1.11.3,<2.0.0_** to **_>=1.14.0,<2.0.0_**, **_dimod 0.8.5_**  upgrated Numpy’s constraint from **_>=1.14.0,<2.0.0_** to **_>=1.15.0,<2.0.0_**, and **_dimod 0.9.0.dev6_** upgrated Numpy’s constraint from **_>=1.15.0,<2.0.0_** to **_>=1.16.0,<2.0.0_**. 

As such, it is a warm warning of a potential dependency conflict issue for dwave-hybrid.

### Dependency tree
```
dwave-hybrid - 0.4.3
| +- click(install version:7.1.1 version range:>5)
| +- dimod(install version:0.9.1 version range:>=0.8.11)
| | +- numpy(install version:1.18.4 version range:>=1.16.0,<2.0.0)
| | +- six(install version:1.14.0 version range:>=1.10.0,<2.0.0)
| +- dwave-neal(install version:0.5.4 version range:>=0.5.1)
| | +- dimod(install version:0.9.1 version range:>=0.7.7)
| | | +- numpy(install version:1.18.4 version range:>=1.16.0,<2.0.0)
| | | +- six(install version:1.14.0 version range:>=1.10.0,<2.0.0)
| | +- numpy(install version:1.18.4 version range:>=1.14.0,<2.0.0)
| | +- six(install version:1.14.0 version range:>=1.11.0,<2.0.0)
| +- dwave-networkx(install version:0.8.6 version range:>=0.6.6)
| | +- decorator(install version:4.4.2 version range:>=4.1.0,<5.0.0)
| | +- dimod(install version:0.9.1 version range:>=0.8.0)
| | | +- numpy(install version:1.18.4 version range:>=1.16.0,<2.0.0)
| | | +- six(install version:1.14.0 version range:>=1.10.0,<2.0.0)
| | +- networkx(install version:2.4 version range:>=2.0,<3.0)
| | | +- decorator(install version:4.4.2 version range:>=4.3.0)
| +- dwave-system(install version:0.9.4 version range:>=0.7.6)
| | +- dimod(install version:0.9.1 version range:>=0.9.0,<0.10.0)
| | | +- numpy(install version:1.18.4 version range:>=1.16.0,<2.0.0)
| | | +- six(install version:1.14.0 version range:>=1.10.0,<2.0.0)
| | +- dwave-cloud-client(install version:0.7.2 version range:>=0.7.2,<0.8.0)
| | | +- click(install version:7.1.1 version range:>=7.0)
| | | +- homebase(install version:1.0.1 version range:>=1.0)
| | | +- plucky(install version: version range:>=0.4.3)
| | | +- python-dateutil(install version:2.8.1 version range:>=2.7)
| | | +- requests(install version:2.23.0 version range:>=2.18)
| | | | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | | | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | | | +- idna(install version:2.9 version range:>=2.5,<3)
| | | | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| | | +- six(install version:1.14.0 version range:>=1.10)
| | +- dwave-networkx(install version:0.8.6 version range:>=0.8.4)
| | | +- decorator(install version:4.4.2 version range:>=4.1.0,<5.0.0)
| | | +- dimod(install version:0.9.1 version range:>=0.8.0)
| | | | +- numpy(install version:1.18.4 version range:>=1.16.0,<2.0.0)
| | | | +- six(install version:1.14.0 version range:>=1.10.0,<2.0.0)
| | | +- networkx(install version:2.4 version range:>=2.0,<3.0)
| | | | +- decorator(install version:4.4.2 version range:>=4.3.0)
| | +- dwave-tabu(install version:0.2.2 version range:>=0.2.0)
| | | +- dimod(install version:0.9.1 version range:>=0.7.9)
| | | | +- numpy(install version:1.18.4 version range:>=1.16.0,<2.0.0)
| | | | +- six(install version:1.14.0 version range:>=1.10.0,<2.0.0)
| | | +- numpy(install version:1.18.4 version range:>=1.14)
| | +- homebase(install version:1.0.1 version range:>=1.0.0,<2.0.0)
| | +- minorminer(install version:0.1.9 version range:>=0.1.3,<0.2.0)
| | +- networkx(install version:2.4 version range:>=2.0,<3.0)
| | | +- decorator(install version:4.4.2 version range:>=4.3.0)
| | +- numpy(install version:1.18.4 version range:>=1.14.0,<2.0.0)
| | +- six(install version:1.14.0 version range:>=1.11.0,<2.0.0)
| +- dwave-tabu(install version:0.2.2 version range:>=0.2.0)
| | +- dimod(install version:0.9.1 version range:>=0.7.9)
| | | +- numpy(install version:1.18.4 version range:>=1.16.0,<2.0.0)
| | | +- six(install version:1.14.0 version range:>=1.10.0,<2.0.0)
| | +- numpy(install version:1.18.4 version range:>=1.14)
| +- minorminer(install version:0.1.9 version range:>=0.1.7)
| +- networkx(install version:2.4 version range:*)
| | +- decorator(install version:4.4.2 version range:>=4.3.0)
| +- numpy(install version:1.18.4 version range:>=1.15.0,<2.0.0)
| +- plucky(install version: version range:>=0.4.3)
| +- six(install version:1.14.0 version range:>=1.10) 
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution 
1.	Loosen the version range of **_numpy_** to be **_>=1.15.0_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_dimod_**.
3.	Change your direct dependency **_dimod_** to be **_>=0.8.11,<=0.9.1_**.
@randomir Which solution do you prefer, 1 ,2 or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by randomir** [comment]
Good catch, thank you @NeolithEra.

To stay consistent with the spirit of other requirements in `dwave-hybrid` (quite loose), I'd go with the first option above (remove the upper bound on `numpy`).

Please feel free to open a PR. Thank you!

**Comment by randomir** [comment]
@NeolithEra, would you like to open a PR with the proposed change (from your branch `patch-1`)?
