### ISSUE TITLE
Better support for (fixed) clique embedding sampling

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dwave-hybrid#225]
An embedding provided on input to `QPUSubproblemExternalEmbeddingSampler` has to be applicable to the current subproblem. In practice, with subproblem changing on each iteration, that means the fixed embedding has to be generated on the fly.

**Comment by arcondello** [comment]
Wouldn't the idea of the `QPUSubproblemExternalEmbeddingSampler` be for decomposition approaches that are known to create a particularly structured subproblem?

**Comment by randomir** [comment]
`QPUSubproblemExternalEmbeddingSampler` requires `embedding` on input, so I'd say it's agnostic to problem structure.

I was thinking to create a block like `SubproblemCliqueEmbedder` which would produce a clique embedding for the input subproblem, so it can be used like this:
```
auto_embedding_sampler = \
    SubproblemCliqueEmbedder(sampler=dwavesampler) | QPUSubproblemExternalEmbeddingSampler(qpu_sampler=dwavesampler)
```

In parallel, it makes sense to create (the missing) `SubproblemEmbedder` which would just use `minorminer.find_embedding()`.
