### ISSUE TITLE
Difference b/w D Wave leap hybrid solver and QBsolv?

### ISSUE THREAD

**Issue by Qudsiaamir** [dwavesystems/dwave-hybrid#245]
what are the principle differences with D Wave leap hybrid solver and QBsolv?

**Comment by randomir** [comment]
Hi @Qudsiaamir,

**QBSolv** is an optimized hybrid solver based on tabu solver, with QPU used for subproblems. It runs on your machine.

**D-Wave Hybrid** is a (Python) framework designed for creating classical-quantum hybrid workflows with an emphasis on ease of use. Simplified implementations of QBSolv in [dwave-hybrid](https://github.com/dwavesystems/dwave-hybrid) are provided as a [two](https://github.com/dwavesystems/dwave-hybrid/blob/master/examples/qbsolv-like.py) workflow construction [examples](https://github.com/dwavesystems/dwave-hybrid/blob/master/examples/qbsolv-like-alt.py). A hybrid workflow will run (i.e. will be orchestrated) from your/local machine, with parts possibly running on a remote system (e.g. Leap). The algorithm and execution flow are completely under developer's control.

**Leap hybrid solver service** is a collection of optimized hybrid solvers based on various classical algorithms, decomposition and hybridization techniques. They are closed-source, proprietary, and hosted on D-Wave cloud, accessible via Solver API as part of the Leap experience. For more details, you might find some of the following whitepapers interesting:
 - [D-Wave Hybrid Solver Service: An Overview](https://www.dwavesys.com/sites/default/files/14-1039A-B_D-Wave_Hybrid_Solver_Service_An_Overview.pdf), 
 - [D-Wave Hybrid Solver Service + Advantage: Technology Update](https://www.dwavesys.com/sites/default/files/14-1048A-A_D-Wave_Hybrid_Solver_Service_plus_Advantage_Technology_Update_0.pdf),
 - [Hybrid Solver for Discrete Quadratic Models](https://www.dwavesys.com/sites/default/files/14-1050A-A_Hybrid_Solver_for_Discrete_Models.pdf)
 - and [a few more](https://www.dwavesys.com/resources/publications?type=white).
